# Generated by Django 4.1.6 on 2023-03-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
