# Generated by Django 4.1.6 on 2023-03-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_brand_car_banrd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='banrd',
            new_name='brand',
        ),
    ]
